all:
  children:
    firewalls:
      hosts:
        # example-firewall:
        #   ansible_host: 10.0.0.1
    switches:
      hosts:
        # example-switch:
        #   ansible_host: 10.0.0.2
    domain_controllers:
      hosts:
        # example-dc:
        #   ansible_host: 10.0.0.3
